name: deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ${GITHUB_SHA::7}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build \
          --build-arg DB_HOST="${{ env.DB_HOST }}" \
          --build-arg DB_USER="${{ env.DB_USER }}" \
          --build-arg DB_PASSWORD="${{ env.DB_PASSWORD }}" \
          -t stream-app . 
          docker tag stream-app ${{ secrets.DOCKER_HUB_USERNAME }}/stream-app:${{ env.SHORT_SHA }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/stream-app:${{ env.SHORT_SHA }}

      - name: SSH Connection and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker rm -f stream-app
            sudo docker system prune -af
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/stream-app:${{ env.SHORT_SHA }}
            sudo docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/stream-app:${{ env.SHORT_SHA }} stream-app
            sudo docker run -d --name stream-app -e TZ=Asia/Seoul -p 8080:8080 stream-app
